name: flutter_cache_manager_hive
description: flutter_cache_manager implementation for hive.
version: 0.0.9
homepage: https://github.com/vishna/flutter_cache_manager_hive

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  clock: ^1.0.1
  file: ^6.1.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  hive: ^2.0.4
  http: ^0.13.0
  meta: ^1.1.8
  path: ^1.6.4
  path_provider: ^2.0.0
  pedantic: ^1.8.0+1
  rxdart: '>=0.26.0 <0.28.0'
  uuid:  ^3.0.4